collections:
  authors:
    output: true

url: "https://www.davidmbaker.dev"
title: David Baker Blog Portfolio and Gallery
description: "My name is David Baker and I'm a full-stack developer. I frequenly post thoughts on my blog, personal projects on my portfolio, or pictures to my gallery."

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag