collections:
  authors:
    output: true

url: "https://www.davidmbaker.dev"
description: "My name is David Baker and I'm a full-stack developer. View my portfolio, blog, gallery."

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag